### ISSUE TITLE
Order of Operation Doesn't Work

### ISSUE THREAD

**Issue by mr-cobg** [utshowmh/func#1]
Conventional order of operation does not work. But, you can group your expressions to give them precedence by using group expression (expression surrounded by parentheses).

**Comment by utshowmh** [comment]
That was because I was parsing multiplicative expression before additive ones. It got fixed in [this](https://github.com/utshowmh/func/commit/8a31ef6df7446e52de6d5fca28550e2fd832eb26) commit.
