### ISSUE TITLE
Inconsistency in error reporting

### ISSUE THREAD

**Issue by mr-cobg** [utshowmh/func#3]
When getting an error, column number are just not consistent. Somtimes, it indicates to the beginig, sometimes in the middle, sometimes in the end.

**Comment by utshowmh** [comment]
I think the parser generating these behaviours. I'll fix it later (since, it's not that big of a deal, for now).

**Comment by utshowmh** [comment]
Error doesn't inform you about column number anymore 😑

**Comment by utshowmh** [comment]
Error doesn't inform you about column number anymore 😑
